// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { MachineDB } from '../machine-db'
import { MachineService } from '../machine.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-machine-detail',
  templateUrl: './machine-detail.component.html',
  styleUrls: ['./machine-detail.component.css']
})
export class MachineDetailComponent implements OnInit {

	// the MachineDB of interest
	machine: MachineDB;

	CleanedlaundryFormControl = new FormControl(false);
	constructor(
		private machineService: MachineService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getMachine();

  }

  getMachine(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.machineService.getMachine(id)
		.subscribe( 
			machine => 
			{ 
					this.machine = machine

					this.CleanedlaundryFormControl.setValue( this.machine.Cleanedlaundry)
        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');

	this.machine.Cleanedlaundry = this.CleanedlaundryFormControl.value



	this.machineService.updateMachine( this.machine )
    .subscribe(machine => {
		this.machineService.MachineServiceChanged.next("update")

    	console.log("machine saved")
    });
  }
}
