// generated by genGoDocs.go
// Package laundromat laundromat backend API
//
// laundromat exposes types of a package.
//
//     Schemes: http
//     BasePath:
//     Version: 0.1
//     Host: localhost:8080
//
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Security:
//     - basic
//
//    SecurityDefinitions:
//    basic:
//      type: basic
//
// swagger:meta
package laundromat
