// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { ActionSinglotonDB } from '../actionsingloton-db'
import { ActionSinglotonService } from '../actionsingloton.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-actionsingloton-detail',
  templateUrl: './actionsingloton-detail.component.html',
  styleUrls: ['./actionsingloton-detail.component.css']
})
export class ActionSinglotonDetailComponent implements OnInit {

	// the ActionSinglotonDB of interest
	actionsingloton: ActionSinglotonDB;

	constructor(
		private actionsinglotonService: ActionSinglotonService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getActionSingloton();

  }

  getActionSingloton(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.actionsinglotonService.getActionSingloton(id)
		.subscribe( 
			actionsingloton => 
			{ 
					this.actionsingloton = actionsingloton

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.actionsinglotonService.updateActionSingloton( this.actionsingloton )
    .subscribe(actionsingloton => {
		this.actionsinglotonService.ActionSinglotonServiceChanged.next("update")

    	console.log("actionsingloton saved")
    });
  }
}
