// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { FieldDB } from '../field-db'
import { FieldService } from '../field.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-field-detail',
  templateUrl: './field-detail.component.html',
  styleUrls: ['./field-detail.component.css']
})
export class FieldDetailComponent implements OnInit {

	// the FieldDB of interest
	field: FieldDB;

	constructor(
		private fieldService: FieldService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getField();

  }

  getField(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.fieldService.getField(id)
		.subscribe( 
			field => 
			{ 
					this.field = field

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.fieldService.updateField( this.field )
    .subscribe(field => {
		this.fieldService.FieldServiceChanged.next("update")

    	console.log("field saved")
    });
  }
}
