// generated by genGoApiFate.go
package models

// APIGateStruct is the struct of the APIGate in the "models" namespace
//
// APIGateStruct enables CRUD of twin instances in the "api" namespace.
//
// APIGateStruct is a gate. It is "closed" or "open".
//
// The gate is "closed" if APIGateCRUDCallbacks is null. It means all operations on an APIGate
// will have no side effect
//
// The gate is "open" if APIGateCRUDCallbacks is not null, the behavior will depends on the implementation
// of the interface
//
// 	swagger:ignore
type APIGateStruct struct {
	APIGateCRUDCallbacks APIGateCRUDCallbacksInterface // pointer to the callback interface
}

// APIGate is a the singloton gate for CRUD operation between "models" and "api" namespace
//
// APIGate is a singloton instance to performs operations between instances in the "models" namespace and instances
// in the "api" namespace
//
// 	swagger:ignore
var APIGate APIGateStruct

// APIGateCRUDCallbacksInterface is the interface that has to be supported
// by the singloton that manages instances in the "api" namespace
//
// Because pointers that implement associations in the "models" space
// cannot be communicated to the front layer and the DB layer,
// they are irrevelant in the "api" namespace and are impletemented with an
// 	ID uint
// this ID can be computed if and only if the associated instance with the pointers has his twin already
// created in the "api" namespace
// therefore, when an "api" twin is created with a call to the "Create" function, the association IDs are not computed.
// They are computed with a call to the "Update" function
//
//	swagger:ignore
type APIGateCRUDCallbacksInterface interface {

	CreateAPIMachine(machine *Machine) (ID uint, err error)
	UpdateAPIMachine(machine *Machine) (ID uint, err error)

	CreateAPIWasher(washer *Washer) (ID uint, err error)
	UpdateAPIWasher(washer *Washer) (ID uint, err error)

}



// CreateAPIMachine creates from machine an instance in the "api" namespace
//
// CreateAPIMachine performs a deep copy of machine fields, if gate is "open"
//
// CreateAPIMachine return the ID of the "api" instance
//
// It updates aPIGateStruct maps of ID to instances and map of instances to ID
func (aPIGateStruct *APIGateStruct) CreateAPIMachine(machine *Machine) (IDAPI uint, err error) {
	if aPIGateStruct.APIGateCRUDCallbacks != nil {
		return aPIGateStruct.APIGateCRUDCallbacks.CreateAPIMachine(machine)
	}
	return
}

// UpdateAPIMachine updates the twin of machine in the "api" namespace with values of machine
//
// UpdateAPIMachine performs a deep copy from from the former to the later
// and computes IDs for the associations
// if gate is "open" CreateAPIMachine return the ID of the "api" instance
func (aPIGateStruct *APIGateStruct) UpdateAPIMachine(machine *Machine) (ID uint, err error) {
	if aPIGateStruct.APIGateCRUDCallbacks != nil {
		return aPIGateStruct.APIGateCRUDCallbacks.UpdateAPIMachine(machine)
	}
	return
}



// CreateAPIWasher creates from washer an instance in the "api" namespace
//
// CreateAPIWasher performs a deep copy of washer fields, if gate is "open"
//
// CreateAPIWasher return the ID of the "api" instance
//
// It updates aPIGateStruct maps of ID to instances and map of instances to ID
func (aPIGateStruct *APIGateStruct) CreateAPIWasher(washer *Washer) (IDAPI uint, err error) {
	if aPIGateStruct.APIGateCRUDCallbacks != nil {
		return aPIGateStruct.APIGateCRUDCallbacks.CreateAPIWasher(washer)
	}
	return
}

// UpdateAPIWasher updates the twin of washer in the "api" namespace with values of washer
//
// UpdateAPIWasher performs a deep copy from from the former to the later
// and computes IDs for the associations
// if gate is "open" CreateAPIWasher return the ID of the "api" instance
func (aPIGateStruct *APIGateStruct) UpdateAPIWasher(washer *Washer) (ID uint, err error) {
	if aPIGateStruct.APIGateCRUDCallbacks != nil {
		return aPIGateStruct.APIGateCRUDCallbacks.UpdateAPIWasher(washer)
	}
	return
}


