// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { DocumentDB } from '../document-db'
import { DocumentService } from '../document.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-document-detail',
  templateUrl: './document-detail.component.html',
  styleUrls: ['./document-detail.component.css']
})
export class DocumentDetailComponent implements OnInit {

	// the DocumentDB of interest
	document: DocumentDB;

	constructor(
		private documentService: DocumentService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getDocument();

  }

  getDocument(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.documentService.getDocument(id)
		.subscribe( 
			document => 
			{ 
					this.document = document

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.documentService.updateDocument( this.document )
    .subscribe(document => {
		this.documentService.DocumentServiceChanged.next("update")

    	console.log("document saved")
    });
  }
}
