// generated by genORMTranslation.go
package orm

import (
	"errors"

	"github.com/jinzhu/gorm"
)

// TranslationImpact distinguish CREATE or UPDATE mode when translating
type TranslationImpact int

const (
	CreateMode TranslationImpact = iota // target objects are not initialized yet
	UpdateMode                          // target objects already exists and are only updated
)

// AllORMStoreStruct supports callback functions
type AllORMStoreStruct struct {
	db *gorm.DB
}

var AllORMStore AllORMStoreStruct

func (allORMStore *AllORMStoreStruct) SetDB(db *gorm.DB) {
	allORMStore.db = db
}

// AllORMToModels init reset all stores of models and orm instances
func AllModelsToORM(db *gorm.DB) (Error error) {


	map_ActionDBID_ActionDB = nil
	map_ActionPtr_ActionDBID = nil
	map_ActionDBID_ActionPtr = nil
	if err := ModelToORMActionTranslate(
		CreateMode,
		db); err != nil {
		return err
	}

	map_AgentDBID_AgentDB = nil
	map_AgentPtr_AgentDBID = nil
	map_AgentDBID_AgentPtr = nil
	if err := ModelToORMAgentTranslate(
		CreateMode,
		db); err != nil {
		return err
	}

	map_EngineDBID_EngineDB = nil
	map_EnginePtr_EngineDBID = nil
	map_EngineDBID_EnginePtr = nil
	if err := ModelToORMEngineTranslate(
		CreateMode,
		db); err != nil {
		return err
	}


	// and now update of the pointer fields
	// now the pointers
	if err := ModelToORMActionTranslate(
		UpdateMode,
		db); err != nil {
		return err
	}
	// now the pointers
	if err := ModelToORMAgentTranslate(
		UpdateMode,
		db); err != nil {
		return err
	}
	// now the pointers
	if err := ModelToORMEngineTranslate(
		UpdateMode,
		db); err != nil {
		return err
	}


	return nil
}

// AllORMToModels update all stores of models to orm instances
func AllModelsUpdateToORM(db *gorm.DB) (Error error) {


	// and now update of the pointer fields
	// now the pointers
	if err := ModelToORMActionTranslate(
		UpdateMode,
		db); err != nil {
		return err
	}
	// now the pointers
	if err := ModelToORMAgentTranslate(
		UpdateMode,
		db); err != nil {
		return err
	}
	// now the pointers
	if err := ModelToORMEngineTranslate(
		UpdateMode,
		db); err != nil {
		return err
	}


	return nil
}


// AllORMToModels init reset all stores of models and orm instances
func AllORMToModels(db *gorm.DB) (Error error) {

	// Init all instances of in the model store

	map_ActionDBID_ActionDB = nil
	map_ActionPtr_ActionDBID = nil
	map_ActionDBID_ActionPtr = nil
	if err := ORMToModelActionTranslate(
		CreateMode, 
		db); err != nil {
		err := errors.New("AllORMToModels, CreateMode Translation of Action failed")
		return err
	}


	map_AgentDBID_AgentDB = nil
	map_AgentPtr_AgentDBID = nil
	map_AgentDBID_AgentPtr = nil
	if err := ORMToModelAgentTranslate(
		CreateMode, 
		db); err != nil {
		err := errors.New("AllORMToModels, CreateMode Translation of Agent failed")
		return err
	}


	map_EngineDBID_EngineDB = nil
	map_EnginePtr_EngineDBID = nil
	map_EngineDBID_EnginePtr = nil
	if err := ORMToModelEngineTranslate(
		CreateMode, 
		db); err != nil {
		err := errors.New("AllORMToModels, CreateMode Translation of Engine failed")
		return err
	}



	if err := ORMToModelActionTranslate(
			UpdateMode, 
			db); err != nil {
		err := errors.New("AllORMToModels, UpdateMode Translation of Action failed")
		return err
	}
	if err := ORMToModelAgentTranslate(
			UpdateMode, 
			db); err != nil {
		err := errors.New("AllORMToModels, UpdateMode Translation of Agent failed")
		return err
	}
	if err := ORMToModelEngineTranslate(
			UpdateMode, 
			db); err != nil {
		err := errors.New("AllORMToModels, UpdateMode Translation of Engine failed")
		return err
	}

	return nil
}

// AllORMUpdateToModels init reset all stores of models and orm instances
func AllORMUpdateToModels(db *gorm.DB) (Error error) {

	// Init all instances of in the model store

	if err := ORMToModelActionTranslate(
			UpdateMode, 
			db); err != nil {
		err := errors.New("AllORMToModels, UpdateMode Translation of Action failed")
		return err
	}
	if err := ORMToModelAgentTranslate(
			UpdateMode, 
			db); err != nil {
		err := errors.New("AllORMToModels, UpdateMode Translation of Agent failed")
		return err
	}
	if err := ORMToModelEngineTranslate(
			UpdateMode, 
			db); err != nil {
		err := errors.New("AllORMToModels, UpdateMode Translation of Engine failed")
		return err
	}

	return nil
}
