// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { GorgoactionDB } from '../gorgoaction-db'
import { GorgoactionService } from '../gorgoaction.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-gorgoaction-detail',
  templateUrl: './gorgoaction-detail.component.html',
  styleUrls: ['./gorgoaction-detail.component.css']
})
export class GorgoactionDetailComponent implements OnInit {

	// the GorgoactionDB of interest
	gorgoaction: GorgoactionDB;

	constructor(
		private gorgoactionService: GorgoactionService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getGorgoaction();

  }

  getGorgoaction(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.gorgoactionService.getGorgoaction(id)
		.subscribe( 
			gorgoaction => 
			{ 
					this.gorgoaction = gorgoaction

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.gorgoactionService.updateGorgoaction( this.gorgoaction )
    .subscribe(gorgoaction => {
		this.gorgoactionService.GorgoactionServiceChanged.next("update")

    	console.log("gorgoaction saved")
    });
  }
}
