// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { VerticeDB } from '../vertice-db'
import { VerticeService } from '../vertice.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-vertice-detail',
  templateUrl: './vertice-detail.component.html',
  styleUrls: ['./vertice-detail.component.css']
})
export class VerticeDetailComponent implements OnInit {

	// the VerticeDB of interest
	vertice: VerticeDB;

	constructor(
		private verticeService: VerticeService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getVertice();

  }

  getVertice(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.verticeService.getVertice(id)
		.subscribe( 
			vertice => 
			{ 
					this.vertice = vertice

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.verticeService.updateVertice( this.vertice )
    .subscribe(vertice => {
		this.verticeService.VerticeServiceChanged.next("update")

    	console.log("vertice saved")
    });
  }
}
