// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { StateDB } from '../state-db'
import { StateService } from '../state.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-state-detail',
  templateUrl: './state-detail.component.html',
  styleUrls: ['./state-detail.component.css']
})
export class StateDetailComponent implements OnInit {

	// the StateDB of interest
	state: StateDB;

	constructor(
		private stateService: StateService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getState();

  }

  getState(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.stateService.getState(id)
		.subscribe( 
			state => 
			{ 
					this.state = state

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.stateService.updateState( this.state )
    .subscribe(state => {
		this.stateService.StateServiceChanged.next("update")

    	console.log("state saved")
    });
  }
}
