// generated by genController.go
package controllers

import (
	"net/http"

	"github.com/thomaspeugeot/metabaron/libs/gorgo/go/models"
	"github.com/thomaspeugeot/metabaron/libs/gorgo/go/orm"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// UmlscSingloton is the type of the singloton of the controllers package
// this singloton allows for the attachment of callbacks to controllers function
type UmlscSingloton struct {
	Callback UmlscCallbackInterface
}

// UmlscCallbackInterface is the interface that must be supported 
// by the Struct that is attached to the singloton
type UmlscCallbackInterface interface {
	PostUmlsc(umlsc *models.Umlsc)
}

// UmlscSinglotonID is the singloton variable
var UmlscSinglotonID UmlscSingloton

// An UmlscID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getUmlsc updateUmlsc deleteUmlsc getUmlscPkgeltsViaUmlscs
type UmlscID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// UmlscInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postUmlsc updateUmlsc
type UmlscInput struct {
	// The Umlsc to submit or modify
	// in: body
	Umlsc *orm.UmlscAPI
}

// GetUmlscs
//
// swagger:route GET /umlscs umlscs getUmlscs
// 
// Get all umlscs
//
// Responses:
//    default: genericError
//        200: umlscDBsResponse
func GetUmlscs(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	var umlscs []orm.UmlscDB
	query := db.Find(&umlscs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	c.JSON(http.StatusOK, umlscs)
}

// PostUmlsc
//
// swagger:route POST /umlscs umlscs postUmlsc
// 
// Creates a umlsc
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: umlscDBResponse
func PostUmlsc(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Validate input
	var input orm.UmlscAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create umlsc
	umlscDB := orm.UmlscDB{}
	umlscDB.UmlscAPI = input

	query := db.Create(&umlscDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	if UmlscSinglotonID.Callback != nil {
		UmlscSinglotonID.Callback.PostUmlsc(&(umlscDB.Umlsc))
	}

	c.JSON(http.StatusOK, umlscDB)
}

// GetUmlsc
//
// swagger:route GET /umlscs/{ID} umlscs getUmlsc
//
// Gets the details for a umlsc.
//
// Responses:
//    default: genericError
//        200: umlscDBResponse
func GetUmlsc(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get umlsc in DB
	var umlsc orm.UmlscDB
	if err := db.First(&umlsc, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	c.JSON(http.StatusOK, umlsc)
}

// UpdateUmlsc
// 
// swagger:route PATCH /umlscs/{ID} umlscs updateUmlsc
//
// Update a umlsc
//
// Responses:
//    default: genericError
//        200: umlscDBResponse
func UpdateUmlsc(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var umlscDB orm.UmlscDB

	// fetch the umlsc
	query := db.First(&umlscDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.UmlscAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update 
	query = db.Model(&umlscDB).Updates(input)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}	

	// return status OK with the marshalling of the the umlscDB
	c.JSON(http.StatusOK, umlscDB)
}

// DeleteUmlsc
//
// swagger:route DELETE /umlscs/{ID} umlscs deleteUmlsc
//
// Delete a umlsc
//
// Responses:
//    default: genericError
func DeleteUmlsc(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var umlscDB orm.UmlscDB
	if err := db.First(&umlscDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&umlscDB)

	c.JSON(http.StatusOK, gin.H{"data": true})
}


// GetUmlscPkgeltsViaUmlscs swagger:route GET /umlscs/{ID}/pkgeltsviaumlscs umlscs getUmlscPkgeltsViaUmlscs
//
// Gets pkgelts of umlsc via field Umlscs of Pkgelt.
//
// Responses:
//    default: genericError
//        200: pkgeltDBsResponse
func GetUmlscPkgeltsViaUmlscs(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get umlsc
	var umlsc orm.UmlscDB
	if err := db.First(&umlsc, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get pkgelts
	var pkgeltDBs orm.PkgeltDBs
	columnName := gorm.ToColumnName("UmlscsID")
	query := db.Where( genQuery(columnName), umlsc.ID).Find(&pkgeltDBs)

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	c.JSON(http.StatusOK, pkgeltDBs)
}

