 // generated by GenNgClass.go

export class MachineDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Cleanedlaundry?: boolean
	DrumLoad?: number
	Name?: string
	RemainingTime?: number
	RemainingTimeMinutes?: number
	State?: string


}
