 // generated by GenNgClass.go

import { MachineDB} from './machine-db'

export class WasherDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	CleanedLaundryWeight?: number
	LaundryWeight?: number
	Name?: string
	State?: string


	Machine?: MachineDB
	MachineID?: number
	MachineName?: string

}
