// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { ActionDB } from '../action-db'
import { ActionService } from '../action.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-action-detail',
  templateUrl: './action-detail.component.html',
  styleUrls: ['./action-detail.component.css']
})
export class ActionDetailComponent implements OnInit {

	// the ActionDB of interest
	action: ActionDB;

	constructor(
		private actionService: ActionService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getAction();

  }

  getAction(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.actionService.getAction(id)
		.subscribe( 
			action => 
			{ 
					this.action = action

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.actionService.updateAction( this.action )
    .subscribe(action => {
		this.actionService.ActionServiceChanged.next("update")

    	console.log("action saved")
    });
  }
}
