// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { ChapterDB } from '../chapter-db'
import { ChapterService } from '../chapter.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-chapter-detail',
  templateUrl: './chapter-detail.component.html',
  styleUrls: ['./chapter-detail.component.css']
})
export class ChapterDetailComponent implements OnInit {

	// the ChapterDB of interest
	chapter: ChapterDB;

	constructor(
		private chapterService: ChapterService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getChapter();

  }

  getChapter(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.chapterService.getChapter(id)
		.subscribe( 
			chapter => 
			{ 
					this.chapter = chapter

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.chapterService.updateChapter( this.chapter )
    .subscribe(chapter => {
		this.chapterService.ChapterServiceChanged.next("update")

    	console.log("chapter saved")
    });
  }
}
