// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { PositionDB } from '../position-db'
import { PositionService } from '../position.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-position-detail',
  templateUrl: './position-detail.component.html',
  styleUrls: ['./position-detail.component.css']
})
export class PositionDetailComponent implements OnInit {

	// the PositionDB of interest
	position: PositionDB;

	constructor(
		private positionService: PositionService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getPosition();

  }

  getPosition(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.positionService.getPosition(id)
		.subscribe( 
			position => 
			{ 
					this.position = position

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.positionService.updatePosition( this.position )
    .subscribe(position => {
		this.positionService.PositionServiceChanged.next("update")

    	console.log("position saved")
    });
  }
}
