 // generated by GenNgClass.go

import { EngineDB} from './engine-db'

export class AgentDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	TechName?: string
	TimeLastChecked?: string
	lastEventTime?: string


	Engine?: EngineDB
	EngineID?: number
	EngineName?: string

}
