 // generated by GenNgClass.go
export class Engine {
	ControlMode?: string
	CurrentTime?: string
	EndTime?: string
	Fired?: number
	Name?: string
	Speed?: number
	StartTime?: string
	State?: string

}
