 // generated by GenNgClass.go

export class EngineDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	ControlMode?: string
	CurrentTime?: string
	EndTime?: string
	Fired?: number
	Name?: string
	Speed?: number
	StartTime?: string
	State?: string


}
