 // generated by GenNgService.go
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Kamar : Ajout d'un moyen pour communiquer entre les composants qui partagent de l'information
 * afin qu'ils soient notifiés d'un changement.
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { MarshallerAPI } from './marshaller-api';
import { MarshallerDB } from './marshaller-db';



@Injectable({
  providedIn: 'root'
})
export class MarshallerService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  MarshallerServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private marshallersUrl = 'http://localhost:8080/marshallers';

  constructor(
    private http: HttpClient
  ) { }

  /** GET marshallers from the server */
  getMarshallers(): Observable<MarshallerDB[]> {
    return this.http.get<MarshallerDB[]>(this.marshallersUrl)
      .pipe(
        tap(_ => this.log('fetched marshallers')),
        catchError(this.handleError<MarshallerDB[]>('getMarshallers', []))
      );
  }

  /** GET marshaller by id. Will 404 if id not found */
  getMarshaller(id: number): Observable<MarshallerDB> {
    const url = `${this.marshallersUrl}/${id}`;
    return this.http.get<MarshallerDB>(url).pipe(
      tap(_ => this.log(`fetched marshaller id=${id}`)),
      catchError(this.handleError<MarshallerDB>(`getMarshaller id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new marshaller to the server */
  postMarshaller(marshallerAPI: MarshallerAPI): Observable<MarshallerDB> {
    return this.http.post<MarshallerDB>(this.marshallersUrl, marshallerAPI, this.httpOptions).pipe(
      tap((newMarshaller: MarshallerDB) => this.log(`added marshaller w/ id=${newMarshaller.ID}`)),
      catchError(this.handleError<MarshallerDB>('addMarshaller'))
    );
  }

  /** DELETE: delete the marshallerdb from the server */
  deleteMarshaller(marshallerdb: MarshallerDB | number): Observable<MarshallerDB> {
    const id = typeof marshallerdb === 'number' ? marshallerdb : marshallerdb.ID;
    const url = `${this.marshallersUrl}/${id}`;

    return this.http.delete<MarshallerDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted marshallerdb id=${id}`)),
      catchError(this.handleError<MarshallerDB>('deleteMarshaller'))
    );
  }

  /** PUT: update the marshallerdb on the server */
  updateMarshaller(marshallerdb: MarshallerDB): Observable<MarshallerDB> {
    const id = typeof marshallerdb === 'number' ? marshallerdb : marshallerdb.ID;
    const url = `${this.marshallersUrl}/${id}`;

    return this.http.put(url, marshallerdb, this.httpOptions).pipe(
      tap(_ => this.log(`updated marshallerdb id=${marshallerdb.ID}`)),
      catchError(this.handleError<MarshallerDB>('updateMarshaller'))
    );
  }



  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
