// generated by genNgDetail.go
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormControl, FormGroup} from '@angular/forms';

import { MarshallerDB } from '../marshaller-db'
import { MarshallerService } from '../marshaller.service'



import { Router, RouterState, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-marshaller-detail',
  templateUrl: './marshaller-detail.component.html',
  styleUrls: ['./marshaller-detail.component.css']
})
export class MarshallerDetailComponent implements OnInit {

	// the MarshallerDB of interest
	marshaller: MarshallerDB;

	constructor(
		private marshallerService: MarshallerService,

		private route: ActivatedRoute,
		private router: Router,
	) {
		// https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
		// this is for routerLink on same component when only queryParameter changes
		this.router.routeReuseStrategy.shouldReuseRoute = function () {
		return false;
		};
  }

  ngOnInit(): void {
	this.getMarshaller();

  }

  getMarshaller(): void {
		const id = +this.route.snapshot.paramMap.get('id');
		this.marshallerService.getMarshaller(id)
		.subscribe( 
			marshaller => 
			{ 
					this.marshaller = marshaller

        }
  	);
  }


  save(): void {
	const id = +this.route.snapshot.paramMap.get('id');




	this.marshallerService.updateMarshaller( this.marshaller )
    .subscribe(marshaller => {
		this.marshallerService.MarshallerServiceChanged.next("update")

    	console.log("marshaller saved")
    });
  }
}
