 // generated by GenNgService.go
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Kamar : Ajout d'un moyen pour communiquer entre les composants qui partagent de l'information
 * afin qu'ils soient notifiés d'un changement.
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ChapterAPI } from './chapter-api';
import { ChapterDB } from './chapter-db';



@Injectable({
  providedIn: 'root'
})
export class ChapterService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ChapterServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private chaptersUrl = 'http://localhost:8080/chapters';

  constructor(
    private http: HttpClient
  ) { }

  /** GET chapters from the server */
  getChapters(): Observable<ChapterDB[]> {
    return this.http.get<ChapterDB[]>(this.chaptersUrl)
      .pipe(
        tap(_ => this.log('fetched chapters')),
        catchError(this.handleError<ChapterDB[]>('getChapters', []))
      );
  }

  /** GET chapter by id. Will 404 if id not found */
  getChapter(id: number): Observable<ChapterDB> {
    const url = `${this.chaptersUrl}/${id}`;
    return this.http.get<ChapterDB>(url).pipe(
      tap(_ => this.log(`fetched chapter id=${id}`)),
      catchError(this.handleError<ChapterDB>(`getChapter id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new chapter to the server */
  postChapter(chapterAPI: ChapterAPI): Observable<ChapterDB> {
    return this.http.post<ChapterDB>(this.chaptersUrl, chapterAPI, this.httpOptions).pipe(
      tap((newChapter: ChapterDB) => this.log(`added chapter w/ id=${newChapter.ID}`)),
      catchError(this.handleError<ChapterDB>('addChapter'))
    );
  }

  /** DELETE: delete the chapterdb from the server */
  deleteChapter(chapterdb: ChapterDB | number): Observable<ChapterDB> {
    const id = typeof chapterdb === 'number' ? chapterdb : chapterdb.ID;
    const url = `${this.chaptersUrl}/${id}`;

    return this.http.delete<ChapterDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted chapterdb id=${id}`)),
      catchError(this.handleError<ChapterDB>('deleteChapter'))
    );
  }

  /** PUT: update the chapterdb on the server */
  updateChapter(chapterdb: ChapterDB): Observable<ChapterDB> {
    const id = typeof chapterdb === 'number' ? chapterdb : chapterdb.ID;
    const url = `${this.chaptersUrl}/${id}`;

    return this.http.put(url, chapterdb, this.httpOptions).pipe(
      tap(_ => this.log(`updated chapterdb id=${chapterdb.ID}`)),
      catchError(this.handleError<ChapterDB>('updateChapter'))
    );
  }



  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
