 // generated by GenNgClass.go

import { FieldDB} from './field-db'

import { LinkDB} from './link-db'

import { PositionDB} from './position-db'

export class ClassshapeDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Heigth?: number
	Name?: string
	Structname?: string
	Width?: number


	Fields?: Array<FieldDB>

	Links?: Array<LinkDB>

	Position?: PositionDB
	PositionID?: number
	PositionName?: string

	// ID generated for the implementation of the field Classshape{}.Classshapes []*Classdiagram
	Classdiagram_ClassshapesDBID?: number

}
