 // generated by GenNgClass.go

import { ClassshapeDB} from './classshape-db'

export class ClassdiagramDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Name?: string


	Classshapes?: Array<ClassshapeDB>

	// ID generated for the implementation of the field Classdiagram{}.Classdiagrams []*Pkgelt
	Pkgelt_ClassdiagramsDBID?: number

}
