 // generated by GenNgClass.go
export class DocumentAPI {

	Author1?: string
	Author1function?: string
	Author2?: string
	Author2function?: string
	Authority?: string
	Authorityfunction?: string
	Date?: string
	Name?: string
	Outputfilepath?: string
	Templatefilepath?: string
	Title?: string
	Verifier?: string
	Verifierfunction?: string

}
