 // generated by GenNgClass.go

import { ChapterDB} from './chapter-db'

export class DocumentDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Author1?: string
	Author1function?: string
	Author2?: string
	Author2function?: string
	Authority?: string
	Authorityfunction?: string
	Date?: string
	Name?: string
	Outputfilepath?: string
	Templatefilepath?: string
	Title?: string
	Verifier?: string
	Verifierfunction?: string


	Chapters?: Array<ChapterDB>

	// ID generated for the implementation of the field Document{}.Documents []*Pkgelt
	Pkgelt_DocumentsDBID?: number

}
