 // generated by GenNgClass.go

export class FieldDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Fieldname?: string
	Fieldtypename?: string
	Name?: string
	Structname?: string


	// ID generated for the implementation of the field Field{}.Fields []*Classshape
	Classshape_FieldsDBID?: number

}
