 // generated by GenNgClass.go

import { VerticeDB} from './vertice-db'

export class LinkDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Fieldname?: string
	Fieldtypename?: string
	Name?: string
	Structname?: string


	Middlevertice?: VerticeDB
	MiddleverticeID?: number
	MiddleverticeName?: string

	// ID generated for the implementation of the field Link{}.Links []*Classshape
	Classshape_LinksDBID?: number

}
