 // generated by GenNgService.go
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Kamar : Ajout d'un moyen pour communiquer entre les composants qui partagent de l'information
 * afin qu'ils soient notifiés d'un changement.
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { PkgeltAPI } from './pkgelt-api';
import { PkgeltDB } from './pkgelt-db';



@Injectable({
  providedIn: 'root'
})
export class PkgeltService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  PkgeltServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private pkgeltsUrl = 'http://localhost:8080/pkgelts';

  constructor(
    private http: HttpClient
  ) { }

  /** GET pkgelts from the server */
  getPkgelts(): Observable<PkgeltDB[]> {
    return this.http.get<PkgeltDB[]>(this.pkgeltsUrl)
      .pipe(
        tap(_ => this.log('fetched pkgelts')),
        catchError(this.handleError<PkgeltDB[]>('getPkgelts', []))
      );
  }

  /** GET pkgelt by id. Will 404 if id not found */
  getPkgelt(id: number): Observable<PkgeltDB> {
    const url = `${this.pkgeltsUrl}/${id}`;
    return this.http.get<PkgeltDB>(url).pipe(
      tap(_ => this.log(`fetched pkgelt id=${id}`)),
      catchError(this.handleError<PkgeltDB>(`getPkgelt id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new pkgelt to the server */
  postPkgelt(pkgeltAPI: PkgeltAPI): Observable<PkgeltDB> {
    return this.http.post<PkgeltDB>(this.pkgeltsUrl, pkgeltAPI, this.httpOptions).pipe(
      tap((newPkgelt: PkgeltDB) => this.log(`added pkgelt w/ id=${newPkgelt.ID}`)),
      catchError(this.handleError<PkgeltDB>('addPkgelt'))
    );
  }

  /** DELETE: delete the pkgeltdb from the server */
  deletePkgelt(pkgeltdb: PkgeltDB | number): Observable<PkgeltDB> {
    const id = typeof pkgeltdb === 'number' ? pkgeltdb : pkgeltdb.ID;
    const url = `${this.pkgeltsUrl}/${id}`;

    return this.http.delete<PkgeltDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted pkgeltdb id=${id}`)),
      catchError(this.handleError<PkgeltDB>('deletePkgelt'))
    );
  }

  /** PUT: update the pkgeltdb on the server */
  updatePkgelt(pkgeltdb: PkgeltDB): Observable<PkgeltDB> {
    const id = typeof pkgeltdb === 'number' ? pkgeltdb : pkgeltdb.ID;
    const url = `${this.pkgeltsUrl}/${id}`;

    return this.http.put(url, pkgeltdb, this.httpOptions).pipe(
      tap(_ => this.log(`updated pkgeltdb id=${pkgeltdb.ID}`)),
      catchError(this.handleError<PkgeltDB>('updatePkgelt'))
    );
  }



  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
