 // generated by GenNgService.go
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Kamar : Ajout d'un moyen pour communiquer entre les composants qui partagent de l'information
 * afin qu'ils soient notifiés d'un changement.
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { StateAPI } from './state-api';
import { StateDB } from './state-db';



@Injectable({
  providedIn: 'root'
})
export class StateService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  StateServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private statesUrl = 'http://localhost:8080/states';

  constructor(
    private http: HttpClient
  ) { }

  /** GET states from the server */
  getStates(): Observable<StateDB[]> {
    return this.http.get<StateDB[]>(this.statesUrl)
      .pipe(
        tap(_ => this.log('fetched states')),
        catchError(this.handleError<StateDB[]>('getStates', []))
      );
  }

  /** GET state by id. Will 404 if id not found */
  getState(id: number): Observable<StateDB> {
    const url = `${this.statesUrl}/${id}`;
    return this.http.get<StateDB>(url).pipe(
      tap(_ => this.log(`fetched state id=${id}`)),
      catchError(this.handleError<StateDB>(`getState id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new state to the server */
  postState(stateAPI: StateAPI): Observable<StateDB> {
    return this.http.post<StateDB>(this.statesUrl, stateAPI, this.httpOptions).pipe(
      tap((newState: StateDB) => this.log(`added state w/ id=${newState.ID}`)),
      catchError(this.handleError<StateDB>('addState'))
    );
  }

  /** DELETE: delete the statedb from the server */
  deleteState(statedb: StateDB | number): Observable<StateDB> {
    const id = typeof statedb === 'number' ? statedb : statedb.ID;
    const url = `${this.statesUrl}/${id}`;

    return this.http.delete<StateDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted statedb id=${id}`)),
      catchError(this.handleError<StateDB>('deleteState'))
    );
  }

  /** PUT: update the statedb on the server */
  updateState(statedb: StateDB): Observable<StateDB> {
    const id = typeof statedb === 'number' ? statedb : statedb.ID;
    const url = `${this.statesUrl}/${id}`;

    return this.http.put(url, statedb, this.httpOptions).pipe(
      tap(_ => this.log(`updated statedb id=${statedb.ID}`)),
      catchError(this.handleError<StateDB>('updateState'))
    );
  }



  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
