 // generated by GenNgClass.go

export class StateDB {
	CreatedAt?: string;
	DeletedAt?: string;
	ID?: number;

	Name?: string
	X?: number
	Y?: number


	// ID generated for the implementation of the field State{}.States []*Umlsc
	Umlsc_StatesDBID?: number

}
