 // generated by GenNgService.go
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Kamar : Ajout d'un moyen pour communiquer entre les composants qui partagent de l'information
 * afin qu'ils soient notifiés d'un changement.
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { VerticeAPI } from './vertice-api';
import { VerticeDB } from './vertice-db';


// import of struct with pointer field to current struct
import { LinkDB} from './link-db'

@Injectable({
  providedIn: 'root'
})
export class VerticeService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  VerticeServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private verticesUrl = 'http://localhost:8080/vertices';

  constructor(
    private http: HttpClient
  ) { }

  /** GET vertices from the server */
  getVertices(): Observable<VerticeDB[]> {
    return this.http.get<VerticeDB[]>(this.verticesUrl)
      .pipe(
        tap(_ => this.log('fetched vertices')),
        catchError(this.handleError<VerticeDB[]>('getVertices', []))
      );
  }

  /** GET vertice by id. Will 404 if id not found */
  getVertice(id: number): Observable<VerticeDB> {
    const url = `${this.verticesUrl}/${id}`;
    return this.http.get<VerticeDB>(url).pipe(
      tap(_ => this.log(`fetched vertice id=${id}`)),
      catchError(this.handleError<VerticeDB>(`getVertice id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new vertice to the server */
  postVertice(verticeAPI: VerticeAPI): Observable<VerticeDB> {
    return this.http.post<VerticeDB>(this.verticesUrl, verticeAPI, this.httpOptions).pipe(
      tap((newVertice: VerticeDB) => this.log(`added vertice w/ id=${newVertice.ID}`)),
      catchError(this.handleError<VerticeDB>('addVertice'))
    );
  }

  /** DELETE: delete the verticedb from the server */
  deleteVertice(verticedb: VerticeDB | number): Observable<VerticeDB> {
    const id = typeof verticedb === 'number' ? verticedb : verticedb.ID;
    const url = `${this.verticesUrl}/${id}`;

    return this.http.delete<VerticeDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted verticedb id=${id}`)),
      catchError(this.handleError<VerticeDB>('deleteVertice'))
    );
  }

  /** PUT: update the verticedb on the server */
  updateVertice(verticedb: VerticeDB): Observable<VerticeDB> {
    const id = typeof verticedb === 'number' ? verticedb : verticedb.ID;
    const url = `${this.verticesUrl}/${id}`;

    return this.http.put(url, verticedb, this.httpOptions).pipe(
      tap(_ => this.log(`updated verticedb id=${verticedb.ID}`)),
      catchError(this.handleError<VerticeDB>('updateVertice'))
    );
  }


    // getter of struct with pointer to current struct
    getVerticeLinksViaMiddlevertice(id: number): Observable<Array<LinkDB>> {
      const url = `${this.verticesUrl}/${id}/linksviamiddlevertice`;
      return this.http.get<Array<LinkDB>>(url).pipe(
        tap(_ => this.log(`fetched vertice id=${id}`)),
        catchError(this.handleError<Array<LinkDB>>(`getVertice id=${id}`))
      );
    }


  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
